// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWy-QREAO92h18DgqQmX_tOV1nhrABTWQ',
    appId: '1:77019528060:web:3bd5b9c988b58b117d02f9',
    messagingSenderId: '77019528060',
    projectId: 'solapp-e41fb',
    authDomain: 'solapp-e41fb.firebaseapp.com',
    storageBucket: 'solapp-e41fb.appspot.com',
    measurementId: 'G-BC2FBQBPLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACFm04Sku8IwICBe6vp665DJRT-pELWYo',
    appId: '1:77019528060:android:26ecb56ab1bb6fd47d02f9',
    messagingSenderId: '77019528060',
    projectId: 'solapp-e41fb',
    storageBucket: 'solapp-e41fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZqqrkaPlbFKEIAtDjh3yBbGtgx9aNlsg',
    appId: '1:77019528060:ios:01c768eaba7bd0417d02f9',
    messagingSenderId: '77019528060',
    projectId: 'solapp-e41fb',
    storageBucket: 'solapp-e41fb.appspot.com',
    iosBundleId: 'com.example.solapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZqqrkaPlbFKEIAtDjh3yBbGtgx9aNlsg',
    appId: '1:77019528060:ios:01c768eaba7bd0417d02f9',
    messagingSenderId: '77019528060',
    projectId: 'solapp-e41fb',
    storageBucket: 'solapp-e41fb.appspot.com',
    iosBundleId: 'com.example.solapp',
  );
}
